### ISSUE TITLE
EMBEDDED - gestione elenco layer

### ISSUE THREAD

**Issue by fgambarelli** [formentinif/likeamap#134]
Se cambio un layer nella mappa principale mi devo ricordare di correggere anche appstate creato per embedded: sarebbe utile che i layer nel file dell'appstate non fossero inseriti ma richiamati dalla mappa main.

**Comment by formentinif** [comment]
Per semplificare la gestione  delle mappe embedded è stata aggiunta una proprietà (embed e prop-embed nell'url) che permette di impostare la mappa embedded in automatico . 
per cui un appstate separato non è più necessario per le mappe embedded, a meno di casi particolari.
