### ISSUE TITLE
Se la chiamata GetRequestInfo restituisce un errore, l'infobox si blocca 

### ISSUE THREAD

**Issue by fgambarelli** [formentinif/likeamap#17]
Verificare la gestione degli errori nel caso una delle chiamate GetRequestInfo restituisca un errore, verificare mappa centro storico layer
https://geoserver.comune.re.it/geoserver/centro_storico/wms/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=centro_storico%3ALINEE_BUS_MINIBUS_E_STOP&LAYERS=centro_storico%3ALINEE_BUS_MINIBUS_E_STOP&SRS=EPSG%3A3857&tiled=true&INFO_FORMAT=text%2Fjavascript&feature_count=50&I=178&J=177&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=1182633.7016282454%2C5574399.598781334%2C1183856.6940808082%2C5575622.591233897&format_options=callback:AppMap.processRequest&callback=jQuery310035526025277173456_1565767232897&_=1565767232904

**Comment by formentinif** [comment]
Issue closed
