### ISSUE TITLE
Revisione dell'infobox

### ISSUE THREAD

**Issue by fgambarelli** [formentinif/likeamap#25]
Visualizzare in prima battuta l'elenco dei layer con risultati. Inserire in alto una nuova di parole con nome del layer e numero dei risultati, al posto di risultati dell'interrogazione.

Cliccando sul nome del layer dovrà essere generato un accordion con l'elenco degli oggetti trovati, utilizzando il titolo definito nel template.
Cliccando sull'oggetto si apre l'oggetto e si zooma in mappa e visulizzarlo con un colore differente (ciano). Viceversa cliccando sulla mappa negli oggetti arancioni deve aprirsi l'accordion con l'oggetto specifico.

**Comment by formentinif** [comment]
Feature added
