### ISSUE TITLE
Eliminazione dell'infobox

### ISSUE THREAD

**Issue by fgambarelli** [formentinif/likeamap#27]
I risultati dell'interrogazione devono essere visualizzati nel menu a lato come in Google. Una volta visualizzati i risultati, l'elenco dei layer può essere attivato cliccando sulla apposita icona. Cliccando nuovamente il tool layer deve essere nascosto con i risultati ancora visibili. Cliccando su di un oggetto in mappa i risultati devono tornare nuovamente disponibili.
Valutare bottone visualizza risultati in alto nell'elenco dei layer

**Comment by formentinif** [comment]
Feature added
