### ISSUE TITLE
Lo zoom di partenza non funziona

### ISSUE THREAD

**Issue by fgambarelli** [formentinif/likeamap#35]
Se non sono impostati anche mapLon e soci lo zoom iniziale non funziona

 "startMapLon": 10.631548456981202,
  "startMapLat": 44.70399735195113,
  "startMapZoom": 12,
  "mapLon": 10.631548456981202,
  "mapLat": 44.70399735195113,
  "mapZoom": 12,

**Comment by formentinif** [comment]
Documentazione aggiornata. Utilizzare le proprietà
"mapLon"
"mapLat"
"mapZoom"
