### ISSUE TITLE
Evitare la sovrapposizione dei pannelli aperti contemporaneamente

### ISSUE THREAD

**Issue by fgambarelli** [formentinif/likeamap#47]
In chrome su mac i pannelli si sovrappongono se aperti contemporaneamente, verificare "Zone della città"

**Comment by formentinif** [comment]
Funzione implementata, verificare su mac.

**Comment by fgambarelli** [comment]
![image](https://user-images.githubusercontent.com/34273200/73002519-7ca1ef00-3e04-11ea-8934-74b6ec27e6ab.png)
