### ISSUE TITLE
Etichetta campo ricerca

### ISSUE THREAD

**Issue by fgambarelli** [formentinif/likeamap#55]
E' possibile cambiare l'etichetta del nome del campo in cui si effettua la ricerca ? Appare il nome della colonna e spesso non è parlante
![image](https://user-images.githubusercontent.com/34273200/71154440-cdd62600-223b-11ea-9b19-d63a4e603b20.png)
Provato ad impostare i seguenti parametri, ma non è variato :
      "searchable": 1,
      "searchField": "ETIC",
      "labelField": "Etichetta",

**Comment by formentinif** [comment]
E' stata aggiunta la proprietà searchFieldLabel per definire l'etichetta da assegnare ai campi di ricerca
