### ISSUE TITLE
Configurazione della cache

### ISSUE THREAD

**Issue by fgambarelli** [formentinif/likeamap#56]
Verificare l'utilizzo della cache da parte di Geoserver. I layer WMS non sono inseriti in una cache a differenza di quanto documentato.
Due chiamate di esempio:

https://geoserver.comune.re.it/geoserver/reggiomap/wms/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=reggiomap%3AANAGRI_CIVICI&SRS=EPSG%3Aundefined&tiled=true&WIDTH=374&HEIGHT=374&CRS=EPSG%3A3857&STYLES=&FORMAT_OPTIONS=dpi%3A132&BBOX=1184162.4421939515%2C5573558.791470196%2C1184238.8792222366%2C5573635.228498481
https://geoserver.comune.re.it/geoserver/gwc/service/wmts?layer=reggiomap%3AANAGRI_CIVICI&style=&tilematrixset=RE_EPSG_3857&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng&TileMatrix=RE_EPSG_3857%3A13&TileCol=4337&TileRow=2955

**Comment by formentinif** [comment]
La cache con geoserver è già abilitata nel WMS e attiva. E' stato risolto un bug dovuto alla mancanza della proprità srid nei layer, a volte scritta in maniera errata "srs"
