### ISSUE TITLE
Metadati base dei layer

### ISSUE THREAD

**Issue by fgambarelli** [formentinif/likeamap#58]
Nella sezione info richiamare un servizio di geoserver che carichi i metadati di base del layer. Il servizio deve essere indicato in una proprietà dello state, e poi la chiamata avverrà su geoserver con il nome del layer

**Comment by fgambarelli** [comment]
Attendere pubblicazione del layer su geoserver con i dati di tutti i layer

**Comment by formentinif** [comment]
Aggiunte le proprietà metaDataServiceUrlTemplate e metaDataTemplate dell'appstate per la gestione dei metadati
