### ISSUE TITLE
Evitare la duplicazione delle label nei group layer

### ISSUE THREAD

**Issue by fgambarelli** [formentinif/likeamap#61]
Verificare che in mappa base l'etichetta del comune non sia duplicata. Avviene solo nei group layer.

**Comment by formentinif** [comment]
Per evitare la duplicazione è necessario aggiungere al textsymbolizer
 <sld:Geometry>
          <ogc:Function name="centroid">
            <ogc:PropertyName>ORA_GEOMETRY</ogc:PropertyName>
          </ogc:Function>
        </sld:Geometry>
