### ISSUE TITLE
Bozza di template per le aree di piantumazione

### ISSUE THREAD

**Issue by fgambarelli** [formentinif/likeamap#89]

**Comment by formentinif** [comment]
{
  "title": "Nuove Piantumazioni",
  "layer": "g001_amb_aree_nuove_piantum",
  "layerGid": "g001_amb_aree_nuove_piantum",
  "templateType": "string",
  "templateString": [
						"<p><strong>NOME</strong>: {{NOME}}</p>",
						"<p><strong>PP_IN_COSTRUZIONE</strong>: {{PP_IN_COSTRUZIONE}}</p>",
						"<p><strong>PP_SCADUTO</strong>: {{PP_SCADUTO}}</p>",
						"<p><strong>NOTE</strong>: {{NOTE}}</p>",
						"<p><strong>PARCO_COLLEGATO</strong>: {{PARCO_COLLEGATO}}</p>",
						"<p><strong>MITIGAZIONE_INFRASTRU</strong>: {{MITIGAZIONE_INFRASTRU}}</p>",
						"<p><strong>RETE_ECOLOGICA</strong>: {{RETE_ECOLOGICA}}</p>",
						"<p><strong>ORIGINE_SEGNALAZIONE</strong>: {{ORIGINE_SEGNALAZIONE}}</p>",
						"<p><strong>AMBITO</strong>: {{AMBITO}}</p>",
						"<p><strong>ZONE_MANUTENZIONE</strong>: {{ZONE_MANUTENZIONE}}</p>",
						"<p><strong>PP_ASSENTE</strong>: {{PP_ASSENTE}}</p>",
						"<p><strong>TIPOLOGIA_AREA</strong>: {{TIPOLOGIA_AREA}}</p>",
						"{{#if RETE_ECOLOGICA}}",
						"<p>Campo RETE_ECOLOGICA presente</p>",
						"{{else}}",
						"<p>Campo RETE_ECOLOGICA non presente</p>",
						"{{/if}}",
						"{{#ifequals RETE_ECOLOGICA Sì}}",
						"<p>Campo RETE_ECOLOGICA == Sì</p>",
						"{{/ifequals}}",
						"{{#ifnotequals RETE_ECOLOGICA Sì}}",
						"<p>Campo RETE_ECOLOGICA != Sì</p>",
						"{{/ifnotequals}}"
						]
}

**Comment by formentinif** [comment]
per creare un template custom impostare il template con tipologia

  "templateType": "string",
e impostare la proprietà
  "templateString"
Questa proprietà può essere una stringa o un array di stringhe (per leggibilità) che saranno poi concatenate.
I valori dell'oggetto saranno sostituiti con i nomi dei campi compresi tra doppie parentesi {{NOME_CAMPO}}
Sono anche disponibili tutti gli helper di handlbars come {{if}} e {{each}}, oltre ai custom helper {{ifequals}} e {{ifnotequals}}
